version: "3.8"

services:
  housekeeping:
    build: .
    container_name: housekeeping
    environment:
      - VIRTUAL_HOST=housekeeping.webpunagaya.com
      - VIRTUAL_PORT=4173
      - LETSENCRYPT_HOST=housekeeping.webpunagaya.com
      - LETSENCRYPT_EMAIL=muhammadirfan187@outlook.com
    expose:
      - "4173"
    networks:
      - proxy
    # depends_on:
    #   - nginx-proxy

networks:
  proxy:
    external: true
